internalName: hdn_keyboard

locales:
  en:
    name: &bundleName "Northern Haida Keyboards"
    description: "Mobile OS keyboards for Northern Haida."
  hdn:
    name: "X̲aad Kíl"
    description: "X̲aad Kíl an stla k̲ʼáalaangwaay."

author: CILLDI, University of Alberta
email: feedback@divvun.no

copyright: (c) 2017 CILLDI
organisation: University of Alberta

layouts: [hdn]

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.__UND__
    icon: images/__UND__-icon.pdf
    keyStore: /Users/brendan/git/softkbdgen/test.keystore
    keyAlias: hdn_keyboard

  ios: &AppleID
    codeSignId: "iOS Development"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.hdn
    bundleName: *bundleName
    icon: images/__UND__-icon.png
  osx: *AppleID
