internalName: hdn_keyboard

locales:
  en:
    name: &bundleName "Northern Haida Keyboards"
    description: "Mobile OS keyboards for Northern Haida."
  hdn:
    name: "X̲aad Kíl"
    description: "X̲aad Kíl an stla k̲ʼáalaangwaay."

author: CILLDI, University of Alberta
email: feedback@divvun.no

copyright: (c) 2017 CILLDI
organisation: University of Alberta

layouts: [hdn]

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.hdn
    icon: images/hdn-icon.pdf
    keyStore: $GTPRIV/admin/dev-accounts/dev_keys/sami_keyboard.keystore
    keyAlias: sami_keyboard

  ios: &AppleID
    codeSignId: "Developer ID Installer: The University of Tromso (2K5J2584NX)"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.hdn
    bundleName: *bundleName
    icon: images/hdn-icon.png

  osx:
    <<: *AppleID
    icon: images/hdn-keyboard-menu-icon.png
    version: 0.1.0
    resources: doc

  win:
    appName: *bundleName
    version: 0.1.0
    url: "http://divvun.no"
    uuid: "replace-with-real-uuid-one-for-each-language"
