internalName: hdn_keyboard

locales:
  en:
    name: &bundleName " Keyboards"
    description: "Mobile OS keyboards for Northern Haida."
  hdn:
    name: "X̲aad Kíl"
    description: "X̲aad Kíl an stla k̲ʼáalaangwaay."

author: The Divvun Group, UiT Norgga árktalaš universitehta
email: feedback@divvun.no

copyright: (c) 2016 Divvun/Giellatekno/UiT
organisation: UiT Norgga árktalaš universitehta

layouts: [hdn]

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.
    icon: sami-icon.pdf
    keyStore: /Users/brendan/git/softkbdgen/test.keystore
    keyAlias: sami_keyboard

  ios: &AppleID
    codeSignId: "iOS Development"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.
    bundleName: *bundleName
    icon:
        90: haida-icon-small.png
        150: sami-icon.png
  osx: *AppleID
